"""Package stage: run summary and optional publish metadata stub."""

from __future__ import annotations

import json
from pathlib import Path

from social_clipr.bundle import (
    BUNDLE_LAYOUT_VERSION,
    METADATA_DRAFT_NAME,
    RUN_SUMMARY_NAME,
    expected_bundle_relative_paths,
    rendered_video_filename,
)


def write_run_summary(
    job_dir: Path,
    *,
    profile: str,
    subtitle_style: str,
    subtitle_font_size_effective: int,
    source_input: Path,
    transcript_json: Path,
    transcript_txt: Path,
    captions_srt: Path,
    captions_vtt: Path,
    rendered_mp4: Path,
    render_mode: str,
    job_preset: str | None = None,
    transcript_source: str | None = None,
) -> Path:
    """Write deterministic run_summary.json under job_dir.

    ``render_mode`` is ``stub_copy`` (input copied, no burn-in) or ``ffmpeg``
    (transcode; subtitles burned when SRT + style were passed to render).
    """
    job_dir = job_dir.resolve()
    source_resolved = source_input.resolve()

    def rel(p: Path) -> str:
        r = p.resolve()
        try:
            return str(r.relative_to(job_dir))
        except ValueError:
            return str(r)

    video_burned_in = render_mode == "ffmpeg"
    manifest = list(expected_bundle_relative_paths(profile))
    summary = {
        "artifacts": {
            "transcript_json": rel(transcript_json),
            "transcript_txt": rel(transcript_txt),
            "captions_srt": rel(captions_srt),
            "captions_vtt": rel(captions_vtt),
            "video_mp4": rel(rendered_mp4),
        },
        "bundle": {
            "expected_files": manifest,
            "layout_version": BUNDLE_LAYOUT_VERSION,
            "naming": {
                "final_video_pattern": "rendered-<encode_profile_id>.mp4",
                "job_folder": "outputs/<input_basename_without_suffix>/",
            },
            "render_mode": render_mode,
            "video_includes_burned_subtitles": video_burned_in,
        },
        "job_dir": str(job_dir),
        "profile": profile,
        "source_input": str(source_resolved),
        "status": "success",
        "stages": ["ingest", "transcribe", "captions", "render", "package"],
        "subtitle_font_size": subtitle_font_size_effective,
        "subtitle_style": subtitle_style,
    }
    if job_preset:
        summary["job_preset"] = job_preset
    if transcript_source is not None:
        summary["transcript_source"] = transcript_source
        summary["transcribe_skipped"] = True
    path = job_dir / RUN_SUMMARY_NAME
    path.write_text(
        json.dumps(summary, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    return path


def write_metadata_draft(
    job_dir: Path,
    *,
    stem: str,
    encode_profile_id: str,
    subtitle_style_id: str,
    subtitle_font_size_effective: int,
    source_filename: str,
    render_mode: str,
    job_preset: str | None = None,
    transcript_source: str | None = None,
) -> Path:
    """Social metadata template aligned with the job bundle (MVP)."""
    payload = {
        "description": "Generated by Social Clipr MVP pipeline.",
        "encode_profile": encode_profile_id,
        "export": {
            "bundle_layout_version": BUNDLE_LAYOUT_VERSION,
            "final_video": rendered_video_filename(encode_profile_id),
            "render_mode": render_mode,
        },
        "hashtags": ["#socialclipr", "#shorts"],
        "source_media": source_filename,
        "subtitle_font_size": subtitle_font_size_effective,
        "subtitle_style": subtitle_style_id,
        "title": f"{stem} — Social Clipr export",
    }
    if job_preset:
        payload["job_preset"] = job_preset
    if transcript_source is not None:
        payload["transcript_source"] = transcript_source
    path = job_dir / METADATA_DRAFT_NAME
    path.write_text(
        json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    return path
